(setq cb/color-theme 'dracula)
(add-hook 'after-init-hook (lambda () (load-theme cb/color-theme t)))
(setq inhibit-default-init t)
(when (display-graphic-p)
  (add-to-list 'default-frame-alist '(foreground-color . "white"))
  (add-to-list 'default-frame-alist '(background-color . "black")))
(setq inhibit-startup-screen t)
(menu-bar-mode -1)
(when (fboundp 'scroll-bar-mode)
  (scroll-bar-mode -1))
(when (fboundp 'tool-bar-mode)
  (tool-bar-mode -1))
(setq-default truncate-lines t)
(setq visible-bell nil
      ring-bell-function 'ignore)
(global-font-lock-mode t)
(show-paren-mode t)
(setq fill-column 70)
(setq-default column-number-mode t)
(display-time)

(provide 'setup-appearance)
