(setq inhibit-default-init t)
(when (string-equal system-type "windows-nt")
  (set-background-color "black")
  (set-foreground-color "white"))
(setq inhibit-startup-screen t)
(menu-bar-mode -1)
(when (fboundp 'scroll-bar-mode)
  (scroll-bar-mode -1))
(when (fboundp 'tool-bar-mode)
  (tool-bar-mode -1))
(setq-default truncate-lines t)
(setq visible-bell t)
(global-font-lock-mode t)
(show-paren-mode t)
(setq fill-column 70)
(setq-default column-number-mode t)
(display-time)

(provide 'setup-appearance)
