(setq disabled-command-function nil)
(fset 'yes-or-no-p 'y-or-n-p)
(setq make-backup-files nil)
(delete-selection-mode 1)
(setq history-delete-duplicates t)
(setq-default comint-input-ignoredups t)
(setq set-mark-command-repeat-pop t)
(setq comment-empty-lines t)
(setq default-input-method 'german-postfix)
(set-language-environment "UTF-8")

(provide 'setup-misc)
